apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.nome | lower | replace(' ', '-') }}
  title: ${{ values.nome | dump }} 
  # namespace: ${{ values.buEcossistema | dump }} #removido pois o namespace qdo diferente de default aparece na lista e no nome (tela) quebrando a tela - viabilizar customizar a tela no futuro se houver necessidade do uso de namespace
  description: ${{ values.descricao | dump }}
  tags:
    ${{ values.tipoExposicaoEModeloAcesso | dump }}
  links:
    - url: ${{ values.urlMonitoramento }}
      title: Dashboard
      icon: dashboard
  annotations:
    backstage.io/source-template: template:default/nova-api
    gov.vr/identificacao.buEcossistema:  ${{ values.buEcossistema | dump }}
    {% if (values.conformidadesRegulamentacoes | default('n/a') | length) > 0 %}
    gov.vr/identificacao.conformidadesRegulamentacoes: ${{ values.conformidadesRegulamentacoes }}
    {% endif %}
    gov.vr/observabilidade.monitoramento: ${{ values.monitoramento }}
    gov.vr/observabilidade.urlMonitoramento: ${{ values.urlMonitoramento }}
    gov.vr/informacao.mensagem: "Pendente de avaliação da Célula Sensedia"
spec:
  type: ${{ values.tipoAPI | dump }}
  lifecycle: Novo
  owner: ${{ values.responsavel | dump }}
  version: ${{ values.versao | dump }}
  {% if (values.servicosExpostos | default([]) | length) > 0 %}
  apiProvidedBy : ${{ values.servicosExpostos | dump }}
  {% endif %}
  definition: ${{ values.urlSwagger | dump }}