apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: novo-microservico
  title: Criar Componente Microserviço
  description: Template para criação de componentes do tipo Microserviço com governança padronizada
spec:
  parameters:
    - title: Nome do Serviço
      description: Nome único do componente
      type: string
      required: true

    - title: Descrição
      description: Breve descrição funcional do componente
      type: string
      required: true

    - title: Owner
      description: Equipe ou pessoa responsável
      type: string
      required: true

    - title: Tipo de Componente
      description: Selecione o tipo
      type: select
      required: true
      options:
        - title: Serviço
          value: service
        - title: Biblioteca
          value: library
        - title: Website
          value: website
        - title: Ferramenta
          value: tool

    - title: Ciclo de Vida
      description: Estado atual do componente
      type: select
      required: true
      options:
        - title: Experimental
          value: experimental
        - title: Produção
          value: production
        - title: Obsoleto
          value: deprecated

    - title: Sistema
      description: Nome do sistema ao qual o componente pertence
      type: string
      required: true

    - title: Domínio Funcional
      description: Área funcional relacionada ao componente
      type: select
      required: true
      options:
        - title: Comum
          value: comum
        - title: Emissor
          value: emissor
        - title: Adquirente
          value: adquirente

  steps:
    - id: criar-repositorio
      name: Criar repositório
      action: scaffolder:publish
      input:
        repoUrl: github.com?repo={{ parameters.nome }}&owner=meu-org
        values:
          name: {{ parameters.nome }}
          description: {{ parameters.descricao }}
          owner: {{ parameters.owner }}
          type: {{ parameters.tipo }}
          lifecycle: {{ parameters.ciclo }}
          system: {{ parameters.sistema }}
          domain: {{ parameters.dominio }}
