apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.nome | dump }}
  description: ${{ values.descricao | dump }}
  tags:
    ${{ values.tipoExposicaoEModeloAcesso | dump }}
  annotations:
    backstage.io/source-template: template:default/novo-componente
    gov.vr.com.br/identificacao/buEcossistema:  ${{ values.buEcossistema | dump }}
    gov.vr.com.br/identificacao/conformidadesRegulamentacoes: ${{ values.conformidadesRegulamentacoes | dump }}
    gov.vr.com.br/observabilidade/capacity: ${{ values.capacity | dump }}
    gov.vr.com.br/observabilidade/sla: ${{ values.sla | dump }}
    gov.vr.com.br/tecnologia/tecnologias: ${{ values.tecnologias | dump }}
    gov.vr.com.br/tecnologia/javaVersion: ${{ values.javaVersion | dump }}
spec:
  type: ${{ values.tipoComponente | dump }}
  lifecycle: Novo
  owner: ${{ values.responsavel | dump }}
  version: ${{ values.versao | dump }}
  consumesApis: ${{ values.apisConsumidas | dump }}
  dependsOn: ${{ values.componentesERecursosDependentes | dump }}
