apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.nome | dump }}
  # namespace: ${{ values.buEcossistema | dump }} #removido pois o namespace qdo diferente de default aparece na lista e no nome (tela) quebrando a tela - viabilizar customizar a tela no futuro se houver necessidade do uso de namespace
  description: ${{ values.descricao | dump }}
  tags:
    ${{ values.tipoExposicaoEModeloAcesso | dump }}
  links:
    - url: ${{ values.urlMonitoramento }}
        title: Dashboard
        icon: dashboard
  annotations:
    backstage.io/source-template: template:default/novo-componente
    gov.vr/identificacao.buEcossistema:  ${{ values.buEcossistema | dump }}
    gov.vr/identificacao.conformidadesRegulamentacoes: ${{ values.conformidadesRegulamentacoes | default('n/a') }}
    gov.vr/detalhamento-tecnico.natureza: ${{ values.natureza }}
    gov.vr/detalhamento-tecnico.cloudProvider: ${{ values.cloudProvider }}
    gov.vr/custo.produtoRelacionado: ${{ values. }}
    gov.vr/custo.centroDeCusto: ${{ values.produtoRelacionado }}
    gov.vr/custo.custo: ${{ values.custo }}
    gov.vr/custo.periodicidade: ${{ values.periodicidade }}
    gov.vr/observabilidade.monitoramento: ${{ values.monitoramento }}
    gov.vr/observabilidade.urlMonitoramento: ${{ values.urlMonitoramento }}
    gov.vr/informacao.mensagem: "Pendente de avaliação da Célula de Infra"
spec:
  type: ${{ values.tipoComponente | dump }}
  lifecycle: Novo
  owner: ${{ values.responsavel | dump }}
  version: ${{ values.versao | dump }}
  {% if (values.componentesConsumidores | default([]) | length) > 0 %}
  dependencyOf : ${{ values.componentesConsumidores | dump }}
  {% endif %}
  {% if (values.recursosDependentes | default([]) | length) > 0 %}
  dependsOn: ${{ values.recursosDependentes | dump }}
  {% endif %}
