apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nova-api
  title: Cadastrar API
  description: Execute para registrar API no catálogo.
spec:
  type: API
  owner: "group:default/gov-vr"
  parameters:
    - title: Identificação
      required: [tipoAPI, nome, descricao, versao, responsavel] 
      properties:
        tipoAPI:
          title: Tipo de API
          type: string
          enum: [OpenAPI, GraphQL, gRPC]
        nome:
          title: Nome
          type: string
          description: "Entre apenas com letras maiúsculas/minúsculas, números, hífen, underscore e espaço. Sempre começe com uma letra. Não é aceito cedilha, acentuação ou caracteres especiais."
          pattern: '^[a-zA-Z][a-zA-Z0-9-_\s]*$'
          errorMessage: 
            pattern: 'Não aceita cedilha, acentos ou caracteres especiais. Somente letras maiúsculas/minúsculas, números, hífen, underscore e espaço. Sempre começe com uma letra.'
        descricao:
          title: Descrição
          description: Breve descrição funcional da API
          type: string
          ui:widget: textarea
          ui:options:
            rows: 5
          ui:help: "Dica: você pode colar texto multilinha aqui."
          ui:placeholder: |
            
            Digite ou cole aqui o seu texto.
            Múltiplas linhas são suportadas.
        versao:
          title: Versão
          description: Versão inicial da API
          type: string
          default: 1.0.0
          pattern: '^\d+\.\d+\.\d+$'
          errorMessage: "Formato de versão inválido. Use o formato X.Y.Z (exemplo: 1.0.0)."
        responsavel:
          title: Time responsável
          description: Time responsável pela API
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group]
            allowArbitraryValues: false
        buEcossistema:
          title: BU do Ecossistema
          type: string
          description: Selecione a BU do ecossistema o qual a API faz parte
          default: vr-beneficios
          enum: [vr-beneficios, vr-gente, vr-mobilidade, vr-shopping, vr-vexpense]
        conformidadesRegulamentacoes:
          title: Conformidade e Regulamentações
          type: array
          items:
            type: string
            enum: [LGPD, PII, ISO9001, ISO25010]
          uniqueItems: true
          ui:widget: checkboxes
    - title: Integração e Consumo
      required: [tipoExposicaoEModeloAcesso]
      properties:
        servicosConsumidos:
          title: Serviços Consumidos
          type: array
          description: Listagem de serviços consumidos
          items:
            type: string
            title: Serviço
            ui:field: EntityPicker
            ui:options:
              catalogFilter:
                kind: Component
          uniqueItems: true
          errorMessage: "O mesmo item foi selecionado mais de uma vez. Favor selecionar somente um de cada."
        tipoExposicaoEModeloAcesso:
            title: Tipo de Exposição e Modelo de Acesso
            type: array
            description: "Selecione as TAGs apropriadas para Modelo de Acesso e Tipo de Exposição."
            items:
              type: string
            minItems: 1
            ui:field: EntityTagsPicker
            ui:options:
              allowArbitraryValues: false
              kinds: [Component]
    - title: Observabilidade
      required: [monitoramento, urlMonitoramento]
      properties:
        monitoramento:
          title: Monitoramento Principal
          type: string
          description: A ferramenta principal utilizada para monitorar este recurso
          enum: [Nativo-Gateway, Dynatrace, Grafana, Zabbix, Prometheus]        
        urlMonitoramento:
          title: URL da Ferramenta de Monitoramento
          type: string
          description: O endereço da ferramenta de monitoramento para reste recurso. 
          pattern: '^http|https://[a-z0-9A-Z]*$'
          errorMessage: "Entre com uma URL HTTP/HTTPS"

    - title: Versionamento
      required: [repoUrl]
      properties:
        repoUrl:
          title: Registro em repositório
          type: string
          description: "Utilizado para manter o catalog-info.yaml deste recurso. Obs: o repositório não deve existir. "
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]
            allowedOwners: [vr-beneficios, vr-gente, vr-mobilidade, vr-shopping, tada-git]
  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          nome: ${{ parameters.nome }}
          descricao: ${{ parameters.descricao | replace(r/\r?\n/g, '\n\r') }}
          tipoAPI: ${{ parameters.tipoAPI }}
          responsavel: ${{ parameters.responsavel }}
          versao: ${{ parameters.versao }}
          buEcossistema:  ${{ parameters.buEcossistema }}
          conformidadesRegulamentacoes: ${{ parameters.conformidadesRegulamentacoes | default([]) | join(', ') }}
          apisConsumidas: ${{ parameters.apisConsumidas }}
          componentesERecursosDependentes: ${{ (parameters.componentesDependentes | default([]) ).concat(parameters.recursosConsumidos | default([]) ) }}
          tipoExposicaoEModeloAcesso: ${{ parameters.tipoExposicaoEModeloAcesso }}
          capacity: ${{ parameters.capacity }}
          sla: ${{ parameters.sla }}
          tecnologias: ${{ parameters.tecnologias | default([]) | join(', ') }}
          javaVersion: ${{ parameters.javaVersion }}
    - id: publish
      name: Publica o repo no github
      action: publish:github
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'Initial: Criacao do repositorio e esqueleto do projeto ${{ parameters.nome }}'
        description: 'Initial: Criacao do repositorio e esqueleto do projeto ${{ parameters.nome }}'
    - id: register
      name: Register
      action: catalog:register
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Abrir no catálogo
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
